### ISSUE TITLE
term colors?

### ISSUE THREAD

**Issue by giulioungaretti** [daynin/dotfiles#1]
how do you set them ?

**Comment by daynin** [comment]
@giulioungaretti I don't set terminal colors in my configs, I just set color themes for vim and tmux. If you want to change terminal's color theme, you can do this by standard way in your OS (and your terminal emulator)

**Comment by giulioungaretti** [comment]
ah, but how  do you get the background of the tmux panes to be the same as say vim ?
asking because I had so many issues getting them to match :D

**Comment by daynin** [comment]
I just use standard color picker for this. Just like that:

![img](https://cloud.githubusercontent.com/assets/825219/14113947/bd6c97ec-f5dd-11e5-9e77-595aab6fd727.png)

**Comment by daynin** [comment]
@giulioungaretti can I close this issue?

**Comment by giulioungaretti** [comment]
## Yep! Thanks 

Giulio Ungaretti
